// apps/backend/src/services/pdfService.ts
import puppeteer from 'puppeteer';
import { IResult } from '../models/Result';
import { IAssignment } from '../models/Assignment';

function difficultyBadge(difficulty: string): string {
  const styles: Record<string, string> = {
    Easy: 'background:#dcfce7;color:#15803d;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;',
    Moderate: 'background:#fef3c7;color:#b45309;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;',
    Hard: 'background:#fee2e2;color:#b91c1c;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;',
  };
  return `<span style="${styles[difficulty] ?? styles['Easy']}">${difficulty}</span>`;
}

function buildHtml(result: IResult, assignment: IAssignment, includeAnswerKey: boolean): string {
  const sectionsHtml = result.sections
    .map(
      (section) => `
      <div style="margin-bottom:24px;">
        <h2 style="text-align:center;font-size:16px;font-weight:700;margin-bottom:4px;">${section.title}</h2>
        <p style="font-weight:700;margin-bottom:2px;">${section.questionType}</p>
        <p style="font-style:italic;margin-bottom:12px;font-size:13px;">${section.instruction}</p>
        ${section.questions
          .map(
            (q) => `
          <p style="margin-bottom:10px;font-size:13px;">
            <strong>${q.number}.</strong> ${difficultyBadge(q.difficulty)} ${q.text}
            <span style="float:right;font-weight:600;">[${q.marks} Mark${q.marks > 1 ? 's' : ''}]</span>
          </p>`
          )
          .join('')}
      </div>`
    )
    .join('');

  const answerKeyHtml = includeAnswerKey
    ? `<div style="margin-top:32px;border-top:2px solid #1A1A1A;padding-top:16px;">
        <h2 style="font-weight:700;font-size:16px;margin-bottom:12px;">Answer Key:</h2>
        ${result.sections
          .map((s) =>
            s.questions
              .map((q) => `<p style="font-size:13px;margin-bottom:6px;"><strong>${q.number}.</strong> ${q.answer}</p>`)
              .join('')
          )
          .join('')}
       </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Times New Roman', serif; font-size: 14px; color: #000; }
    .clearfix::after { content: ''; display: table; clear: both; }
  </style>
</head>
<body style="padding: 40px;">
  <div style="text-align:center;margin-bottom:20px;">
    <h1 style="font-size:20px;font-weight:700;">${assignment.schoolName}</h1>
    <p style="font-size:14px;margin-top:4px;">Subject: ${assignment.subject}</p>
    <p style="font-size:14px;">Class: ${assignment.className}</p>
  </div>

  <div class="clearfix" style="margin-bottom:12px;">
    <span style="float:left;">Time Allowed: ${assignment.timeAllowed} minutes</span>
    <span style="float:right;">Maximum Marks: ${result.totalMarks}</span>
  </div>

  <p style="font-weight:700;margin-bottom:16px;">All questions are compulsory unless stated otherwise.</p>

  <div style="margin-bottom:20px;border-top:1px solid #000;padding-top:12px;">
    <p style="margin-bottom:8px;">Name: _______________________________________________</p>
    <p style="margin-bottom:8px;">Roll Number: _______________________________________</p>
    <p>Class: ${assignment.className} &nbsp;&nbsp; Section: ________________</p>
  </div>

  <hr style="border:1px solid #000;margin-bottom:20px;">

  ${sectionsHtml}

  <p style="text-align:center;font-weight:700;margin-top:32px;border-top:1px solid #000;padding-top:16px;">
    — End of Question Paper —
  </p>

  ${answerKeyHtml}

  <p style="font-size:10px;color:#666;text-align:center;margin-top:24px;border-top:1px solid #ddd;padding-top:8px;">
    Generated by VedaAI &bull; OpenCode Zen &bull; ${new Date(result.generatedAt).toLocaleString()} &bull; Version ${result.version}
  </p>
</body>
</html>`;
}

export async function generatePdf(
  result: IResult,
  assignment: IAssignment,
  includeAnswerKey: boolean
): Promise<Buffer> {
  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.setContent(buildHtml(result, assignment, includeAnswerKey), { waitUntil: 'networkidle0' });
  const pdf = await page.pdf({ format: 'A4', margin: { top: '2cm', right: '2cm', bottom: '2cm', left: '2cm' }, printBackground: true });
  await browser.close();
  return Buffer.from(pdf);
}
